import unittest
import os
from src.main import Main, Growth


class TestGetGrowth(unittest.TestCase):
    """Test `get_growth()` method."""

    def setUp(self):
        """Create Tasks objects for the three testing cases."""
        data_dir = os.path.dirname(__file__) + "/../data"
        df_10 = Main(f"{data_dir}/ten.csv").get_data()
        self.tasks_10 = Growth(df_10)
        df_50 = Main(f"{data_dir}/fifty.csv").get_data()
        self.tasks_50 = Growth(df_50)
        df = Main(f"{data_dir}/full_data.csv").get_data()
        self.tasks_all = Growth(df)

    def test_multiple_entries(self):
        """Test case 1 using full_data.csv."""
        actual_result = self.tasks_all.get_growth()
        expected_result = [
            "Bytedance",
            "SpaceX",
            "Stripe",
            "Klarna",
            "Epic Games",
            "Canva",
            "Checkout.com",
            "Instacart",
            "Databricks",
            "Revolut",
            "FTX",
            "Fanatics",
            "Chime",
            "BYJU's",
            "Xiaohongshu",
            "J&T Express",
            "Miro",
            "Yuanfudao",
            "DJI Innovations",
            "SHEIN",
            "goPuff",
            "Yuanqi Senlin",
            "Ripple",
            "Plaid",
            "OpenSea",
            "Grammarly",
            "Devoted Health",
            "Faire",
            "Brex",
            "JUUL Labs",
            "Bitmain Technologies",
            "Biosplice Therapeutics",
            "GoodLeap",
            "Airtable",
            "ZongMu Technology",
            "Celonis",
            "Bolt",
            "Alchemy",
            "Weilong",
            "Swiggy",
            "Lalamove",
            "Figma",
            "Gusto",
            "reddit",
            "Talkdesk",
            "Notion Labs",
            "Thrasio",
            "Digital Currency Group",
            "OutSystems",
            "ServiceTitan",
            "HEYTEA",
            "N26",
            "Klaviyo",
            "Tanium",
            "Chehaoduo",
            "Niantic",
            "OYO Rooms",
            "Rapyd",
            "Kavak",
            "Snyk",
            "Nuro",
            "Bolt",
            "Lacework",
            "Tipalti",
            "Tempus",
            "Dream11",
            "Fireblocks",
            "Ramp",
            "Flexport",
            "Caris Life Sciences",
            "Dapper Labs",
            "Hopin",
            "Getir",
            "Netskope",
            "Razorpay",
            "Toss",
            "Carta",
            "Argo AI",
            "Gong",
            "TripActions",
            "Gemini",
            "We Doctor",
            "Discord",
            "Ro",
            "Automation Anywhere",
            "1Password",
            "Ziroom",
            "National Stock Exchange of India",
            "Mollie",
            "Rippling",
            "DataRobot",
            "Personio",
            "Upgrade",
            "Hinge Health",
            "Black Unicorn Factory",
            "Benchling",
            "Royole Corporation",
            "Better.com",
            "Wiz",
            "iCapital Network",
            "Pine Labs",
            "6Sense",
            "Attentive",
            "Easyhome",
            "Lianjia",
            "Vice Media",
            "Cityblock Health",
            "Workato",
            "Back Market",
            "RELEX Solutions",
            "Postman",
            "FiveTran",
            "Pony.ai",
            "Trade Republic",
            "Rappi",
            "Collibra",
            "Blockchain.com",
            "OneTrust",
            "QuintoAndar",
            "C6 Bank",
            "United Imaging Healthcare",
            "Deel",
            "Airwallex",
            "Mambu",
            "Horizon Robotics",
            "Howden Group Holdings",
            "SambaNova Systems",
            "ZEPZ",
            "OakNorth Bank",
            "Moon Active",
            "OfBusiness",
            "Cockroach Labs",
            "Qonto",
            "Ola Electric Mobility",
            "Icertis",
            "Hopper",
            "Meesho",
            "Creditas",
            "Chipone",
            "Pleo",
            "Anduril",
            "Lyra Health",
            "Dataiku",
            "Checkr",
            "Color",
            "Meizu Technology",
            "Vinted",
            "VIPKid",
            "Socure",
            "UBTECH Robotics",
            "Outreach",
            "WeRide",
            "BetterUp",
            "Arctic Wolf Networks",
            "Sorare",
            "Relativity Space",
            "Miaoshou Doctor",
            "Chainalysis",
            "ThoughtSpot",
            "Globalization Partners",
            "dbt Labs",
            "SSENSE",
            "Dataminr",
            "BitPanda",
            "Weee!",
            "Houzz",
            "CRED",
            "Yello Mobile",
            "MEGVII",
            "Greensill",
            "Radiology Partners",
            "Next Insurance",
            "Patreon",
            "PointClickCare",
            "Zapier",
            "Clubhouse",
            "BrowserStack",
            "Olive",
            "Rubrik",
            "Melio",
            "Vuori",
            "ClickUp",
            "Cerebras Systems",
            "Farmers Business Network",
            "Branch",
            "Aurora Solar",
            "Medlinker",
            "Intarcia Therapeutics",
            "StockX",
            "MessageBird",
            "Guild Education",
            "Articulate",
            "FalconX",
            "Dutchie",
            "Cohesity",
            "VAST Data",
            "GOAT",
            "Noom",
            "Redwood Materials",
            "Papaya Global",
            "ShareChat",
            "Relativity",
            "Whoop",
            "Applied Intuition",
            "Course Hero",
            "Otto Bock HealthCare",
            "Indigo Ag",
            "HyalRoute",
            "Rec Room",
            "Digit Insurance",
            "Commure",
            "Mirakl",
            "Coalition",
            "Tekion",
            "Celsius Network",
            "GoStudent",
            "Highspot",
            "Handshake",
            "ChargeBee Technologies",
            "Flock Safety",
            "Unacademy",
            "MoonPay",
            "Upstox",
            "Youxia Motors",
            "OwnBackup",
            "Cloudwalk",
            "ECARX",
            "Sila Nanotechnologies",
            "Scopely",
            "Komodo Health",
            "Kurly",
            "Cars24",
            "BlockDaemon",
            "Dadi Cinema",
            "Thumbtack",
            "Cedar",
            "Eruditus Executive Education",
            "Blockstream",
            "ConsenSys",
            "Innovaccer",
            "Ironclad",
            "Skims",
            "PsiQuantum",
            "SpotOn",
            "Udaan",
            "HighRadius",
            "Nuvemshop",
            "DailyHunt",
            "Yixia",
            "Traveloka",
            "SouChe Holdings",
            "BGL Group",
            "Circle",
            "Delhivery",
            "FlixMobility",
            "Wildlife Studios",
            "ApplyBoard",
            "Forter",
            "Calendly",
            "BlockFi",
            "ActiveCampaign",
            "CMR Surgical",
            "Lucid Software",
            "Age of Learning",
            "Carbon Health",
            "Contentful",
            "LaunchDarkly",
            "Seismic",
            "Grafana Labs",
            "Gorillas",
            "Sky Mavis",
            "Outschool",
            "TradingView",
            "Groww",
            "Podium",
            "Via",
            "Anchorage Digital",
            "Inxeption",
            "Lattice",
            "Flutterwave",
            "Amber Group",
            "Kraken",
            "OpenAI",
            "Ovo",
            "Workrise",
            "Loft",
            "BharatPe",
            "DriveWealth",
            "Flink",
            "Meicai",
            "ContentSquare",
            "Zipline",
            "Graphcore",
            "Illumio",
            "Convoy",
            "MasterClass",
            "Dream Games",
            "Transmit Security",
            "Tradeshift",
            "Nextiva",
            "o9 Solutions",
            "ManoMano",
            "Sourcegraph",
            "Pendo",
            "Plume",
            "Moglix",
            "JumpCloud",
            "Vista Global",
            "BYTON",
            "Acronis",
            "Side",
            "Lenskart",
            "Infra.Market",
            "Varo Bank",
            "Cato Networks",
            "Aura",
            "Vercel",
            "Sysdig",
            "Zetwerk",
            "Uniphore",
            "Somatus",
            "Uala",
            "Mobile Premier League",
            "Cybereason",
            "Cgtz",
            "Star Charge",
            "Carbon",
            "PolicyBazaar",
            "Exabeam",
            "BitSight Technologies",
            "Trumid",
            "ABL Space Systems",
            "Project44",
            "Bought By Many",
            "Jobandtalent",
            "WEMAKEPRICE",
            "Biren Technology",
            "Voodoo",
            "Uptake",
            "KeepTruckin",
            "Greenlight",
            "Bowery Farming",
            "Odoo",
            "MoMo",
            "Ankorstore",
            "Zume",
            "Algolia",
            "Pattern",
            "MUSINSA",
            "Current",
            "Bitso",
            "Gympass",
            "Reify Health",
            "Dialpad",
            "G7 Networks",
            "BloomReach",
            "Huaqin Telecom Technology",
            "Accelerant",
            "Hesai Tech",
            "YITU Technology",
            "Addepar",
            "Neo4j",
            "CloudWalk",
            "FirstCry",
            "Eightfold.ai",
            "Webflow",
            "Urban Company",
            "Moveworks",
            "Medable",
            "SoundHound",
            "GoCardless",
            "Trendy Group International",
            "Tubatu.com",
            "BlaBlaCar",
            "HuiMin",
            "Quora",
            "Improbable",
            "Preferred Networks",
            "Formlabs",
            "4Paradigm",
            "Calm",
            "Kaseya",
            "Mafengwo",
            "Druva",
            "Kujiale",
            "AppsFlyer",
            "Keep",
            "Redis Labs",
            "Xingyun Group",
            "Unqork",
            "Virta Health",
            "Earnix",
            "Guoquan Shihui",
            "Arrail Dental",
            "Clearco",
            "Hive",
            "KRY",
            "Kajabi",
            "Ethos",
            "PayFit",
            "Beisen",
            "Pipe",
            "Iterable",
            "Bunq",
            "Clip",
            "Loggi",
            "MURAL",
            "Pagaya",
            "OCSiAl",
            "XtalPi",
            "Apeel Sciences",
            "Opay",
            "Aviatrix",
            "SmartNews",
            "Misfits Market",
            "Spring Health",
            "Black Sesame Technologies",
            "Advance Intelligence Group",
            "Modern Treasury",
            "Tier",
            "Aiven",
            "ClickHouse",
            "Mynt",
            "Everlaw",
            "Zilch",
            "VerbIT",
            "StarkWare",
            "Netlify",
            "Deliverr",
            "SWORD Health",
            "LTK",
            "Exotec",
            "Dremio",
            "Akulaku",
            "Fenbi Education",
            "Starling Bank",
            "Rokt",
            "InVision",
            "eDaili",
            "MX Technologies",
            "Aledade",
            "CoinSwitch Kuber",
            "CFGI",
            "Retool",
            "Automattic",
            "ZocDoc",
            "Diamond Foundry",
            "FullStory",
            "Lightricks",
            "Opentrons",
            "AIWAYS",
            "Trulioo",
            "Spinny",
            "Orca Security",
            "Apus Group",
            "Harry's",
            "PAX",
            "DispatchHealth",
            "Unite Us",
            "CircleCI",
            "Wave",
            "Vestiaire Collective",
            "Dragos",
            "Reltio",
            "H2O.ai",
            "ZenBusiness",
            "Carsome",
            "Productboard",
            "Spotter",
            "Alan",
            "Hibob",
            "Trader Interactive",
            "Jusfoun Big Data",
            "Transcarent",
            "DealShare",
            "Zhubajie",
            "solarisBank",
            "Infinidat",
            "Afiniti",
            "Verkada",
            "Clari",
            "Tonal",
            "Clio",
            "SafetyCulture",
            "Extend",
            "Cognite",
            "ASAPP",
            "SmartHR",
            "Mercury",
            "HomeLight",
            "Truepill",
            "ezCater",
            "Wayflyer",
            "Promasidor Holdings",
            "Baiwang",
            "Iluvatar CoreX",
            "Wenheyou",
            "Loom",
            "Ximalaya FM",
            "Mu Sigma",
            "Mofang Living",
            "DT Dream",
            "Changingedu",
            "XiaoZhu",
            "JOLLY Information Technology",
            "Yijiupi",
            "Cambridge Mobile Telematics",
            "Collective Health",
            "Strava",
            "Zenoti",
            "K Health",
            "Uplight",
            "ID.me",
            "Snapdocs",
            "Chipper Cash",
            "Ledger",
            "Next Silicon",
            "YunQuNa",
            "Impact",
            "SmartRecruiters",
            "NotCo",
            "Culture Amp",
            "TaxBit",
            "1047 Games",
            "Matillion",
            "Persona",
            "Whatnot",
            "Ascend Money",
            "Andela",
            "Built",
            "candy.com",
            "Devo",
            "CoinList",
            "Lusha",
            "CureFit",
            "Solugen",
            "Olist",
            "Paradox",
            "Airbyte",
            "StoreDot",
            "Il Makiage",
            "Spendesk",
            "Veriff",
            "Athelas",
            "ElasticRun",
            "Veho",
            "Temporal",
            "Fabric",
            "Yipin Shengxian",
            "Bordrin Motors",
            "Coocaa",
            "Juma Peisong",
            "Ouyeel",
            "Gymshark",
            "Zeta",
            "M1 Finance",
            "Aleo",
            "Einride",
            "Justworks",
            "SonderMind",
            "Papa",
            "Figment",
            "Envoy",
            "Deliverect",
            "SparkCognition",
            "Firebolt",
            "Koudai",
            "Symphony",
            "Yidian Zixun",
            "Cabify",
            "Deezer",
            "Away",
            "Kong",
            "Epidemic Sound",
            "Yotpo",
            "Rebel Foods",
            "Coda",
            "Five Star Business Finance",
            "Stash",
            "Phenom People",
            "GupShup",
            "Degreed",
            "Astranis Space Technologies",
            "Scalable Capital",
            "VideoAmp",
            "Panther Labs",
            "Salt Security",
            "Tripledot Studios",
            "Veepee",
            "DeepBlue Technology",
            "Yaoshibang",
            "At-Bay",
            "Alloy",
            "Epirus",
            "Signifyd",
            "Motorway",
            "RIDI",
            "Flipboard",
            "Grove Collaborative",
            "GPclub",
            "Tongdun Technology",
            "Athletic Greens",
            "Unisound",
            "Alzheon",
            "HeartFlow",
            "InSightec",
            "Everly Health",
            "Manner",
            "TalkingData",
            "Betterment",
            "Flock Freight",
            "YugaByte",
            "Lukka",
            "TravelPerk",
            "iTrustCapital",
            "Domestika",
            "CoinTracker",
            "Loadsmart",
            "TUNGEE",
            "Starry",
            "Intercom",
            "OVO Energy",
            "Huisuanzhang",
            "WTOIP",
            "BigID",
            "Kuaikan Manhua",
            "Marshmallow",
            "Honor Technology",
            "Mythical Games",
            "Incode Technologies",
            "Tackle.io",
            "Flipdish",
            "Route",
            "CaptivateIQ",
            "BrewDog",
            "Enflame",
            "Nexii",
            "Insider",
            "Fair",
            "Glossier",
            "Workhuman",
            "Qumulo",
            "Tealium",
            "Public",
            "Axonius",
            "Savage X Fenty",
            "Pipa Coding",
            "Aibee",
            "Vectra Networks",
            "Ada Support",
            "Inari",
            "Alation",
            "SmartMore",
            "Rohlik",
            "Prime Medicine",
            "FloQast",
            "MindTickle",
            "UpGrad",
            "DailyPay",
            "Oda",
            "Offchain Labs",
            "Copado",
            "Gem",
            "CarDekho",
            "MyGlamm",
            "AgentSync",
            "Pristyn Care",
            "Jokr",
            "Merama",
            "SeekOut",
            "BigPanda",
            "Phantom",
            "LivSpace",
            "Xpressbees",
            "Helium Systems",
            "CloudBees",
            "L&P Cosmetic",
            "Luoji Siwei",
            "Yimidida",
            "Modern Health",
            "IRL",
            "LifeMiles",
            "Venafi",
            "Guideline",
            "Rebellion Defense",
            "Elemy",
            "Happy Money",
            "Doctolib",
            "STORD",
            "TELD",
            "TangoMe",
            "Juanpi",
            "Ivalua",
            "Sisense",
            "Pharmapacks",
            "Sennder",
            "Nexthink",
            "Zego",
            "Rightway",
            "Sunbit",
            "Qingting FM",
            "G2",
            "Hailo",
            "People.ai",
            "CoinDCX",
            "Carousell",
            "apna",
            "Karat",
            "Acko General Insurance",
            "Daily Harvest",
            "The Bank of London",
            "Turing",
            "GlobalBees",
            "LEAD School",
            "eSentire",
            "Beyond Identity",
            "Nxin",
            "UISEE Technology",
            "56PINGTAI",
            "Rubicon",
            "Radius Payment Solutions",
            "Rivigo",
            "Mamaearth",
            "Jiuxian",
            "Instabase",
            "Sendbird",
            "Density",
            "Mixpanel",
            "Aprogen",
            "OrCam Technologies",
            "Lookout",
            "TechStyle Fashion Group",
            "LinkSure Network",
            "BeiBei",
            "Lamabang",
            "JimuBox",
            "BenevolentAI",
            "FXiaoKe",
            "Vox Media",
            "Mia.com",
            "58 Daojia",
            "Womai",
            "HuJiang",
            "iTutorGroup",
            "MindMaze",
            "iCarbonX",
            "SMS Assist",
            "Mobvoi",
            "Modernizing Medicine",
            "Zhaogang",
            "YH Global",
            "Revolution Precrafted",
            "Maimai",
            "Orbbec Technology",
            "HMD Global",
            "Huike Group",
            "LinkDoc Technology",
            "Movile",
            "Pat McGrath Labs",
            "Wacai",
            "FlashEx",
            "Tresata",
            "Hosjoy",
            "Omio",
            "BitFury",
            "Geek+",
            "REEF Technology",
            "Globality",
            "Ynsect",
            "Intellifusion",
            "Liquid",
            "VTS",
            "KnowBox",
            "Meero",
            "Ibotta",
            "Numbrs",
            "EBANX",
            "KK Group",
            "Hotmart",
            "Emerging Markets Property Group",
            "Quizlet",
            "Orca Bio",
            "Playco",
            "Socar",
            "Gousto",
            "Boom Supersonic",
            "Qualia",
            "Quantum Metric",
            "News Break",
            "MadeiraMadeira",
            "PPRO",
            "Splashtop",
            "DriveNets",
            "Flash Express",
            "Axiom Space",
            "Locus Robotics",
            "Standard",
            "Sentry",
            "WeBull",
            "Skydio",
            "Newsela",
            "Aqua Security",
            "PatSnap",
            "Evidation",
            "Sidecar Health",
            "Feedzai",
            "Yunxuetang",
            "Cameo",
            "Fetch Rewards",
            "Hyperchain",
            "The Zebra",
            "Clearcover",
            "Groq",
            "Fiture",
            "Injective Protocol",
            "Sift",
            "SaltPay",
            "MOLOCO",
            "Mux",
            "XForcePlus",
            "Firefly Aerospace",
            "HoneyBook",
            "Shift Technology",
            "TensTorrent",
            "Zihaiguo",
            "Forte Labs",
            "Axtria",
            "Amount",
            "Vise",
            "Printful",
            "Matrixport",
            "Shippo",
            "Thirty Madison",
            "LetsGetChecked",
            "EcoFlow",
            "Tractable",
            "Bringg",
            "JoyTunes",
            "Aircall",
            "SmartAsset",
            "Morning Consult",
            "Visier",
            "ShipBob",
            "MobileCoin",
            "Lunar",
            "Amperity",
            "Remote",
            "Pantheon Systems",
            "GO1",
            "Interos",
            "BlackBuck",
            "NIUM",
            "Unico",
            "Human Interest",
            "Bluecore",
            "Freshbooks",
            "Snorkel AI",
            "Gelato",
            "Maven Clinic",
            "Dunamu",
            "Shield AI",
            "PicsArt",
            "1KMXC",
            "Cider",
            "Agile Robots",
            "GrubMarket",
            "Xendit",
            "TrueLayer",
            "PandaDoc",
            "Keenon Robotics",
            "HAYDON",
            "Vedantu",
            "TrialSpark",
            "Ajaib",
            "Licious",
            "Masterworks",
            "Chronosphere",
            "Solo.io",
            "Swile",
            "MobiKwik",
            "Dental Monitoring",
            "CargoX",
            "Augury",
            "Moka",
            "Tezign",
            "Vagaro",
            "Drata",
            "OpenWeb",
            "Contrast Security",
            "Wrapbook",
            "Gaussian Robotics",
            "Mensa Brands",
            "Heyday",
            "PLACE",
            "Stytch",
            "Owkin",
            "Expel",
            "NoBroker",
            "Slice",
            "Thought Machine",
            "Lessen",
            "Clara",
            "YipitData",
            "Anyscale",
            "ReliaQuest",
            "Pet Circle",
            "Lydia",
            "SnapLogic",
            "Cadence",
            "Noname Security",
            "Rothy's",
            "Haomao.AI",
            "Kopi Kenangan",
            "ONE",
            "CAIS",
            "Placer.ai",
            "Pentera",
            "Darwinbox",
            "Minio",
            "Fever Labs",
            "Esusu",
            "Betterfly",
            "Dune Analytics",
            "Scandit",
            "Payhawk",
            "Watershed",
            "Axelar",
            "CHEQ",
            "Hasura",
            "Timescale",
            "Omada Health",
        ]
        self.assertEqual(actual_result, expected_result)

    def test_fifty_entries(self):
        """Test case 2 using fifty.csv with fifty rows."""
        actual_result = self.tasks_50.get_growth()
        expected_result = [
            "Bytedance",
            "SpaceX",
            "Stripe",
            "Klarna",
            "Epic Games",
            "Canva",
            "Checkout.com",
            "Instacart",
            "Databricks",
            "Revolut",
            "FTX",
            "Fanatics",
            "Chime",
            "BYJU's",
            "Xiaohongshu",
            "J&T Express",
            "Miro",
            "Yuanfudao",
            "DJI Innovations",
            "SHEIN",
            "goPuff",
            "Yuanqi Senlin",
            "Ripple",
            "Plaid",
            "OpenSea",
            "Grammarly",
            "Devoted Health",
            "Faire",
            "Brex",
            "JUUL Labs",
            "Bitmain Technologies",
            "Biosplice Therapeutics",
            "GoodLeap",
            "Airtable",
            "ZongMu Technology",
            "Celonis",
            "Bolt",
            "Alchemy",
            "Weilong",
            "Swiggy",
            "Lalamove",
            "Figma",
            "Gusto",
            "reddit",
            "Talkdesk",
            "Notion Labs",
            "Thrasio",
            "Digital Currency Group",
            "OutSystems",
        ]
        self.assertEqual(actual_result, expected_result)

    def test_ten_entries(self):
        """Test case 3 using ten.csv with ten rows."""
        actual_result = self.tasks_10.get_growth()
        expected_result = [
            "Bytedance",
            "SpaceX",
            "Stripe",
            "Klarna",
            "Epic Games",
            "Canva",
            "Checkout.com",
            "Instacart",
            "Databricks",
        ]
        self.assertEqual(actual_result, expected_result)


if __name__ == "__main__":
    unittest.main()
