import unittest
import os
from src.main import Main, Investors


class TestGetInverstors(unittest.TestCase):
    """Test `get_investors()` method."""

    def setUp(self):
        """Create Tasks objects for the three testing cases."""
        data_dir = os.path.dirname(__file__) + "/../data"
        df_10 = Main(f"{data_dir}/ten.csv").get_data()
        self.tasks_10 = Investors(df_10)
        df_50 = Main(f"{data_dir}/fifty.csv").get_data()
        self.tasks_50 = Investors(df_50)
        df = Main(f"{data_dir}/full_data.csv").get_data()
        self.tasks_all = Investors(df)

    def test_multiple_entries(self):
        """Test case 1 using full_data.csv."""
        actual_result = self.tasks_all.get_investors()
        expected_result = [
            "Fashion Tech Lab",
            "Pereg Ventures",
            "Info Edge",
            "Addition",
            "Dynamo VC",
            "Green Innovations",
            "Group 11",
            "Tengelmann Ventures",
            "Susquehanna Growth Equity",
            "CPP Investment Board",
            "Vertex Ventures SE Asia",
            "Uniion Square Ventures",
            "Goldcrest Capital",
            "TopoScend Capital",
            "Mobai Capital",
            "Providence Ventures",
            "eWTP Capital",
            "Activant Capital",
            "Knox Lane",
            "8VC",
            "Streamlined Ventures",
            "Flybridge Capital Partners",
            "Tiger Global",
            "Blue Lake Capital",
            "Delta Capital",
            "Technology Crossover Ventures",
            "Vintage Investment Partners",
            "Innovation Endeavors",
            "Anthermis",
            "Evolution Equity Partners",
            "Linear Venture",
            "One Peak Partners",
            "Aviv Venture Capital",
            "Group GSR Ventures",
            "Plug and Play Ventures",
            "Dell Technologies Capital",
            "Storm Ventures",
            "Framework Ventures",
            "Vista Equity Partners",
            "SAIF Partners",
            "Eniac Ventures",
            "Point72 Ventures",
            "Gaorong Capital",
            "Coltrane Asset Management",
            "Caterpillar",
            "Javelin Venture Partners",
            "Gobi Partners",
            "Point Nine Capital",
            "Future Ventures",
            "Summer Capital",
            "Khosla Ventures,General Catalyst",
            "Triangle Peak Partners",
            "Promus Ventures",
            "Rusnano",
            "Japan Post Capital",
            "BlockTower Capital",
            "BA Capital",
            "Piton Capital",
            "Guozhong Venture Capital Management",
            "Founders Fund",
            "Helion Venture Partners",
            "FirstMark Capital",
            "Shenzhen Capital Group",
            "DCM Ventures",
            "Rhone Capital",
            "83North",
            "Green Visor Capital",
            "frst",
            "dRx Capital",
            "Sutter Hill Ventures",
            "Northzone Ventures",
            "York Capital Management",
            "Danhua Capital",
            "GLP Capital Partners",
            "Nine Intelligence Capital",
            "Asset Management Ventures",
            "Alpargatas",
            "Mangrove Capital Partners",
            "Inspiration Ventures",
            "Hinduja Group",
            "Homebrew",
            "CRE Venture Capital",
            "Newion Partners",
            "Genesis Partners",
            "TTV Capital",
            "Bitmain Technologies",
            "Eastern Bell Capital 32",
            "DT Capital Partners",
            "Dragonfly Capital Partners",
            "PayPal Ventures",
            "Redpoint Ventures",
            "East Ventures",
            "Oak HC/FT Partners",
            "North Bridge Growth Equity",
            "Rocketship.vc",
            "Edison Partners",
            "Schonfeld Strategic Advisors",
            "Temasek",
            "Kraken Ventures",
            "IMM Investment",
            "Alven Capital",
            "AllegisCyber Capital",
            "Canapi Ventures",
            "Draper Fisher Jurvetson",
            "Lightbox Ventures",
            "Struck Capital",
            "Hongxiu VC",
            "Ribbit Capital",
            "China Everbright Investment Management",
            "Resolute Ventures",
            "Georgian Co-Investment Fund",
            "CVC Capital Partners",
            "Insight Partners",
            "Unilever Ventures",
            "Tiger Global management",
            "Liberty Global Ventures",
            "Speedinvest",
            "A91 Partners",
            "Opus Capital",
            "E Fund",
            "Initialized Capital",
            "360 Capital Partners",
            "Deer Park Road",
            "Mangrove Capital Partners,14W. ForgeLight",
            "NJF Capital",
            "Global Asset Capital",
            "Woori Investment",
            "China Construction Bank",
            "Oriza Holdings",
            "A&NN",
            "American Express Ventures",
            "HarbourVest Partners",
            "Cambridge Innovation Capital",
            "Lead Edge Capital",
            "Siam Commercial Bank",
            "Echo Health Venturesl",
            "Quantum Energy Partners",
            "QiMing Venture Partners",
            "Tencent Holdings",
            "Qatar Investment Authority",
            "Rich Land Capital",
            "Wamda Capital",
            "Lightspeed Venture Partners",
            "Canaan Partners",
            "Trifecta Capital",
            "Newpath Partners",
            "Silverton Partners",
            "White Star Capital",
            "Morningside Group",
            "Tianjin Haihe Industry Fund",
            "Maniv Mobility",
            "Socii Capital",
            "Section 32",
            "Yinhong Equity Investment Fund",
            "14W",
            "Forerunner Ventures",
            "Playground Global",
            "Broom Ventures",
            "Pelion Venture Partners",
            "New Leaf Venture Partners",
            "Index Ventures",
            "Walden International",
            "Ant Financial Services Group",
            "ClalTech",
            "Acero Capital",
            "Cathay Innovation",
            "Highland Europe",
            "Insights Venture Partners",
            "Nor-Cal Invest",
            "Octopus Ventures",
            "SOSV",
            "DJF",
            "Falcon Edge Capital",
            "Goldstone Investments",
            "Balderton Capital",
            "SAP.iO Fund",
            "Lindeman Asia Investment",
            "MMC Ventures",
            "Songhyun Investment",
            "The Carlyle Group",
            "Commerce Ventures",
            "Ivy Capital",
            "HOF Capital",
            "Founder H Fund",
            "LeapFrog Investments",
            "Hanaco Ventures",
            "JAFCO Co",
            "FreesFund",
            "GIC",
            "Huasheng Capital",
            "Vcanbio",
            "500 Global",
            "China International Capital Corporation",
            "Advantech Capital",
            "Energy Impact Partners",
            "TMT Investments",
            "K9 Ventures",
            "SIG Asia Investments",
            "Spark Capital",
            "Jump Capital",
            "Monashees+",
            "Alta Partners",
            "Dark Horse Technology Group",
            "AltaIR Capital",
            "Kleiner Perkins Caufield & Byers",
            "World Innovation Lab",
            "Passion Capital",
            "FundersClub",
            "iFly",
            "FTV Capital",
            "LGT Capital Partners",
            "Advent International",
            "Russia-China Investment Fund",
            "Scentan Ventures",
            "Cybernaut Growth Fund",
            "DN Capital",
            "Battery Ventures",
            "IDG Capital Partners",
            "World Lab Innovation",
            "Chuanrong Capital",
            "KCK Group",
            "BGF Ventures",
            "ZhenFund",
            "Auriga",
            "Flagship Pioneering",
            "China Reform Fund",
            "Nichi-Iko Pharmaceutical",
            "500 Startups",
            "Female Founders Fund",
            "GAM Holding",
            "Grandland",
            "Kite Ventures",
            "Shenzhen Qianhe Capital Management Co.",
            "Baillie Gifford & Co.",
            "Lightspeed Venture Capital",
            "U.S.-China Green Fund",
            "Galaxy Digital",
            "iVision Ventures",
            "Airbus Ventures",
            "Lone Pine Capital",
            "Sodexo Ventures",
            "Digital Currency Group",
            "One Luxury Group",
            "Volcanics Ventures",
            "Bain Capital",
            "Wanxin Media",
            "Slack Fund",
            "The Rise Fund",
            "Paradigm",
            "Maverick Ventures",
            "Tokopedia",
            "Tenaya Capital",
            "Earlybird Venture Capital",
            "Tomales Bay Capital",
            "Meritech Capital Partners",
            "Wipro Ventures",
            "3L",
            "Silk Road Huacheng",
            "UBS Asset Management",
            "SC.Holdings",
            "Sequoia Capital",
            "Ten Eleven Ventures",
            "Sound Ventures",
            "TQ Ventures",
            "Novator Partners",
            "Tencent Investment",
            "Ayala Corporation",
            "Prometheus Capital",
            "Ardian",
            "Paladin Capital Group",
            "SingTel Innov8",
            "Lemniscap VC",
            "RRE Ventures+",
            "Salesforce Ventures",
            "Shunwei Capital Partners",
            "EQT Ventures",
            "Orange Digital Ventures",
            "F-Prime Capital",
            "Future Perfect Ventures",
            "3one4 Capital Partners",
            "Greyhound Capital",
            "Tus Holdings",
            "CMFG Ventures",
            "QF Capital",
            "Mizuho Financial Group",
            "Centralway",
            "STRIVE",
            "Formation 8",
            "Amplify Partners",
            "New Era Ventures",
            "Hedosophia",
            "EXOR Seeds",
            "Iconiq Capital",
            "Diamler",
            "LTW Capital",
            "3i Group",
            "Sequoia Capital India",
            "Left Lane Capital",
            "Banyan Capital",
            "Max Ventures",
            ".406 Ventures",
            "Vickers Venture Partners",
            "Hillhouse Capital Management",
            "Ally Bridge Group",
            "Trane Technologies",
            "Jungle Ventures",
            "Georgian Partners",
            "General Catalyst Partners",
            "Blackbird Ventures",
            "Robert Bosch Venture Capital",
            "Norma Investments",
            "China Culture Industrial Investment Fund",
            "Motive Partners. Apollo Global Management",
            "Jiangsu Sha Steel Group",
            "SEED Capital",
            "Prysm Capital",
            "Longitude Capital",
            "Sina Weibo",
            "Anthos Capital",
            "Soros Fund Management",
            "GGV Capital",
            "US Venture Partners",
            "Gaopeng Capital",
            "AXA Venture Partners",
            "KKR",
            "Leonardo DiCaprio",
            "SBI Investment",
            "JBV Capital",
            "Draper Esprit",
            "Atop Capital",
            "Chengwei Capital",
            "Crowdcube",
            "Jackson Square Ventures",
            "Elaia Partners",
            "DST Global",
            "CRV",
            "Y Combinator",
            "SAIF Partners China",
            "SAIF Partners India",
            "B Capital Group",
            "GE Healthcare",
            "PremjiInvest",
            "BlueCross BlueShield Venture Partners",
            "IKEA GreenTech",
            "Quiet Capital",
            "Pokemon Company International",
            "Fidelity Investments",
            "China Media Group",
            "Hongdao Capital",
            "General Atlantic",
            "Sunley House Capital Management",
            "Zhangjiang Haocheng Venture Capital",
            "NightDragon Security",
            "Maveron",
            "China Creation Ventures",
            "Tribe Capital",
            "Valar Ventures",
            "Warbug Pincus",
            "Connect Ventures",
            "ICG",
            "Capital One Growth Ventures",
            "Yunfeng Capital",
            "Nintendo",
            "Lux Capital",
            "Bertelsmann India Investments",
            "Relay Ventures",
            "Aviation Industry Corporation of China",
            "Amadeus Capital Partners",
            "Liberty City Ventures",
            "Foxconn Technology Company",
            "Magma Venture Partners",
            "Lenovo Capital and Incubator",
            "Lightrock",
            "Iris Capital",
            "Crosslink Capital",
            "Stripe",
            "Navitas Capital",
            "Morningside Ventures",
            "Insight Venture Partners",
            "Prosus Ventures",
            "Founders",
            "Leaders Fund",
            "Venture Highway",
            "Beijing Juneng Hesheng Industry Investment Fund",
            "Ginko Ventures",
            "Greylock Partners",
            "WestCap Group",
            "Elevation Capital",
            "FutureX Capital",
            "Sinovation Ventures",
            "Bedrock Capital",
            "India Quotient",
            "Ainge Advisory",
            "Kickstart Fund",
            "Brighton Park Capital",
            "Felix Capital",
            "Smash Ventures",
            "Accel",
            "Two Sigma Ventures",
            "AME Cloud Ventures",
            "TDM Growth Partners",
            "Acton Capital Partners",
            "Blackrock",
            "Launchpad Venture Group",
            "IndexVentures",
            "McKesson Ventures",
            "Rothenberg Ventures",
            "The Blue Venture Fund",
            "Obvious Ventures",
            "GreatPoint Ventures",
            "Operator Collective",
            "Group11",
            "Ventech China",
            "We Capital",
            "Adams Street Partners",
            "Spar Capital",
            "3G Capital Management",
            "NIO Capital",
            "Andreessen Horowitz",
            "Accel India",
            "Beijing Shuju Xinrong Fund",
            "The Times Group",
            "\tSummit Partners",
            "Tokyo Century Corporation",
            "Unicom Innovation Venture Capital",
            "Bloomberg Beta",
            "SoftBank Group. Monashees+",
            "North Island Ventures",
            "Credit Suisse",
            "IA Ventures",
            "FinVC",
            "Loeb.NYC",
            "Geodesic Capital",
            "Cedarlake Capital",
            "Temasek,\tBUILD Capital Partners",
            "BoxGroup",
            "Ventura Capital",
            "Green Pine Capital Partners",
            "OMERS Private Equity",
            "L'Occitane",
            "VebVentures",
            "Greenoaks Capital Management",
            "Eight Roads Ventures",
            "Sixth Street Partners",
            "American Family Ventures",
            "Oryzn Capital",
            "Bregal Sagemount",
            "Alexandria Venture Investments",
            "Pritzker Group Venture Capital",
            "Johnson & Johnson Innovation",
            "Bolt Ventures",
            "Sino-Ocean Capital",
            "s28 Capital",
            "Portag3 Ventures",
            "Spectrum Equity",
            "Tao Capital Partners",
            "Matrix Partners",
            "Sequoia Capital China",
            "Morgan Creek Digital",
            "Bertelsmann Asia Investments",
            "Foundry Group",
            "Davidson Kempner Capital Management",
            "VGames",
            "Verizon Ventures",
            "Valor Capital Group",
            "Vulcan Capital",
            "Moore Strategic Ventures",
            "BNP Paribas",
            "Alliance Consumer Growth",
            "Altos Ventures",
            "CommerzVentures",
            "Vast Ventures",
            "SOFTBANK Latin America Ventures",
            "Sofinnova Partners",
            "B Capital Group,",
            "CMB International Capital",
            "\tNorthzone Ventures",
            "Microsoft ScaleUp",
            "Pitango Venture Capital",
            "Collaborative Fund",
            "Union Square Ventures",
            "Eleven Ventures",
            "Optum Ventures",
            "Oceanwide Holdings",
            "Zheshang Venture Capital",
            "Breyer Capital",
            "Google Ventures",
            "Geekdom Fund",
            "Fabric Ventures",
            "Ant Group",
            "Presidio Ventures",
            "Alta Ventures Mexico",
            "Kinnevik",
            "IQ Capital",
            "Atomico",
            "Hillsven Capital",
            "Vision Knight Capital",
            "Didi Chuxing",
            "and Sequoia Capital China",
            "Amasia",
            "DFJ Growth Fund",
            "China Life Insurance",
            "IDInvest Partners",
            "Bessemer Venture Partners",
            "Matrix Partners India",
            "Rethink Impact",
            "Simon Equity Partners",
            "Epiq Capital",
            "Bright Venture Capita",
            "Workday Ventures",
            "Legend Capital",
            "SeptWolves Ventures",
            "Cowboy Ventures",
            "VentureLink",
            "Vitruvian Partners",
            "UBS",
            "Alibaba Pictures Group",
            "Felicis Ventures",
            "ConsenSys Ventures",
            "Capital Today",
            "Craft Ventures",
            "WestBridge Capital",
            "Longzhu Capital",
            "Rho Ventures",
            "Thrive Capital",
            "OrbiMed Advisors",
            "Seaya Ventures",
            "Gaocheng Capital",
            "Cox Enterprises",
            "R-Z Capital",
            "FTX Venture",
            "MSA Capital",
            "XVC Venture Capital",
            "Eclipse Ventures",
            "Kaszek Ventures",
            "GF Investments",
            "Gradient Ventures",
            "Global Founders Capital",
            "UNITY VENTURES",
            "Multicoin Capital",
            "SK Ventures",
            "Maersk Growth",
            "Costanoa Ventures",
            "Qiming Venture Partners",
            "Raven One Ventures",
            "Tiantu Capital",
            "Caffeinated Capital",
            "Toyota Motor Corporation",
            "Standard Crypto",
            "T. Rowe Price",
            "Unternehmertum Venture Capital",
            "Undisclosed",
            "JOY Capital",
            "LocalGlobe",
            "Inflexion Private Equity",
            "Lupa Systems",
            "Bow Wave Capital",
            "Menlo Ventures",
            "ACE & Company",
            "International Finance Corporation",
            "RTP Global",
            "SignalFire",
            "Fontinalis Partners",
            "Hummingbird Ventures",
            "Kerala Ventures",
            "JD Digits",
            "Ascension Ventures",
            "Jinhui Xingye",
            "Google Capital",
            "Emergence Capital Partners",
            "YL Ventures",
            "Bond",
            "ICONIQ Growth",
            "Altamont Capital Partners",
            "Krungsri Finnovate",
            "Electric Capital",
            "Crossbeam Venture Partners",
            "Andalusian Capital Partners",
            "Avenir Growth Capital",
            "Clermont Group",
            "Square Peg Capital",
            "S Capital",
            "Thoma Bravo",
            "Baidu Ventures",
            "Sierra Ventures",
            "Barter Ventures",
            "ES Ventures",
            "Tiger Global Management",
            "Webb Investment Network",
            "Das Capital",
            "China Minsheng Investment",
            "Meituan Dianping",
            "Xingwang Investment Management",
            "Viking Global Investors",
            "Revolution",
            "British Patient Capital",
            "Aglae Ventures",
            "Blockchain Capital",
            "M12",
            "Jove Equity Partners",
            "None",
            "Kalaari Capital",
            "Imaginary Ventures",
            "Ideal International",
            "Sequoia Capital Israel",
            "XAnge Private Equity",
            "Boxin Capital",
            "China Investment Corporation",
            "Lightbank",
            "China Development Bank Capital",
            "Runa Capital",
            "Yinxinggu Capital",
            "Hyde Park Venture Partners",
            "Afore Capital",
            "Fireside Ventures",
            "Fosun RZ Capital",
            "Bain Capital Tech Opportunities",
            "Hearst Ventures",
            "NGP Capital",
            "Qatar Holding",
            "Bank of China",
            "Tencent",
            "Thirty Five Ventures",
            "Coatue Managemeny",
            "Galaxy Interactive",
            "Dila Capital",
            "BlueRun Ventures",
            "HCA Healthcare",
            "Teamworthy Ventures",
            "Next World Capital",
            "New Enterprise Associates",
            "Investment Corporation of Dubai",
            "Thrity Five Ventures",
            "Phoenix New Media",
            "Picus Capital",
            "Peterson Ventures",
            "Transamerica Ventures",
            "IDG Capital",
            "Valor Equity Partners",
            "TAL Education Group",
            "Oriental Fortune Capital",
            "Bain Capital Ventures",
            "Gauss Ventures",
            "Tiantu Capital Co.",
            "True Ventures",
            "Threshold Ventures",
            "Mubadala Capital",
            "L Catterton",
            "Wavemaker Partners",
            "Times Internet",
            "GS Growth",
            "Bond Capital",
            "BOC International",
            "Core Capital Partners",
            "Sands Capital",
            "WRVI Capital",
            "General Catalyst",
            "Mitsubishi Corporation",
            "Floodgate",
            "Cocnord Health Partners",
            "Insights Partners",
            "Meridian Capital",
            "Innova Capital - FIP",
            "Goldman Sachs",
            "Eastern Bell Capital",
            "Temasek Holdings",
            "\t01 Advisors",
            "Yunqi Partners",
            "Go-Ventures",
            "Morningside Venture Capital",
            "Blue Cloud Ventures",
            "Revolution Growth",
            "First Light Capital Group",
            "Doha Venture Capital",
            "Anthemis",
            "Coinbase Ventures",
            "Inova Ventures Participacees",
            "10T Fund",
            "CMC Capital Partners",
            "Rakuten",
            "Hanwha Investment & Securities",
            "Steadview Capital",
            "Partech Partners",
            "Flare Capital Partners",
            "Menlo Ventures,Crosslink Capital",
            "Wincove",
            "Taigang Venture Capital",
            "Quadrille Capital",
            "Mayfair Equity Partners",
            "GoldenTree Asset Management",
            "Accelm Scania Growth Capital",
            "Passport Capital",
            "Revo Capital",
            "Guangdong Technology Financial Group",
            "Data Collective",
            "Bojiang Capital",
            "Merieux Equity Partners",
            "LowercaseCapital",
            "Shasta Ventures",
            "Investcorp",
            "BDT Capital Partners",
            "Fifth Wall Ventures",
            "Harrison Metal",
            "Crane Venture Partners",
            "Silver Lake",
            "Sky9 Capital",
            "Walden Venture Capital",
            "Draper Fisher Jurtson",
            "Madrona Venture Group",
            "Atinum Investment",
            "Citi Ventures",
            "ICONIQ Capital",
            "Route 66 Ventures",
            "Deciens Capital",
            "VY Capital",
            "NXC",
            "capitalG",
            "Carsales",
            "Franklin Templeton",
            "Eurazeo",
            "March Capital Partners",
            "Escala Capital",
            "Third Point",
            "iTech Capital",
            "SoftBank Latin America Fund",
            "Capricorn Investment Group",
            "BEENEXT",
            "Norwest Venture Partners",
            "Highland Capital Partners",
            "First Round Capital",
            "Ping An Insurance",
            "Griffin Gaming Partners",
            "XBTO Ventures",
            "Aleph",
            "SV Angel",
            "index Ventures",
            "Woodford Investment Management",
            "Astral Capital",
            "BMW i Ventures",
            "Francisco Partners",
            "U.S. Venture Partners",
            "Kaalari Capital",
            "Qualcomm Ventures",
            "Glory Ventures",
            "CreditEase Fintech Investment Fund",
            "Guangzhou Huiyin Aofeng Equity Investment Fund",
            "Kibo Ventures",
            "Aspect Ventures",
            "Noshaq",
            "Alpha JWC Ventures",
            "Endiya Partners",
            "Notion Capital",
            "BlackRock",
            "Perpetual Investors",
            "INGKA Investments",
            "Google",
            "Softbank",
            "BPI France",
            "Israel Growth Partners",
            "The Venture Collective",
            "Xiang He Capital",
            "SoftBank Group",
            "D1 Capital Partners",
            "Skip Capital",
            "AWZ Ventures",
            "Volkswagen Group",
            "TLV Partners",
            "\tICONIQ Capital",
            "Hony Capital",
            "Work-Bench",
            "Shea Ventures",
            "RiverPark Ventures",
            "T. Rowe Associates",
            "Marcy Venture Partners",
            "Creandum",
            "Mountain Nazca",
            "MHS Capital",
            "Sixth Street Growth",
            "Comcast Ventures",
            "Silversmith Capital Partners",
            "Redpoint e.ventures",
            "Lerer Hippeau",
            "Light Street Capital",
            "Amiti Ventures",
            "Providence Equity Partners",
            "JD Capital Management",
            "Horizons Ventures",
            "Moore Capital Management",
            "Nyca Partners",
            "Korelya Capital",
            "Ondine Capital",
            "\tHuman Capital",
            "L Capital Partners",
            "Redalpine Venture Partners",
            "Next Play Ventures",
            "GX Capital",
            "Gunosy Capital",
            "Daphni",
            "Baidu",
            "CSC Group",
            "SCB 10X",
            "Charoen Pokphand Group",
            "Moonshots Capital",
            "Endeavor",
            "Cadenza Ventures",
            "Marchmont Ventures",
            "Alkeon Capital Management",
            "Hellman & Friedman",
            "DataTribe",
            "5Y Capital",
            "Aker",
            "Ford Autonomous Vehicles",
            "Maverick Capital",
            "Eldridge",
            "Samsung Ventures",
            "Northern Light Venture Capital",
            "Durable Capital Partners",
            "Kenetic Capital",
            "Rubicon Technology Partners",
            "Highland Capital Management",
            "SmartFin Capital",
            "JTC Group",
            "DESUN Capital",
            "A&E Television Networks",
            "Ding Xiang Capital",
            "Polychain Capital",
            "Lakestar",
            "Delian Capital",
            "Charter Venture Capital",
            "China Renaissance",
            "Harvey Golub Family Office",
            "Longfor Capitalm",
            "Summit Partners",
            "Pine Brook",
            "PSG",
            "Grand Flight Investment",
            "Bain & Company",
            "Blumberg Capital",
            "Brookfield Asset Management",
            "Bonfire Ventures",
            "Hopu Investment Management",
            "K2 Ventures",
            "TDR Capital",
            "Softbank Capital",
            "RPM Ventures",
            "Tru Arrow Partners",
            "China Health Industry Investment Fund",
            "Jerusalem Venture Partners",
            "Ajinomoto",
            "Burda Principal Investments",
            "Victory Park Capital",
            "Accel Partners",
            "Foundation Capital",
            "QED Investors",
            "TSG Consumer Partners",
            "MaC Venture Capital",
            "Scale Venture Partners",
            "CyberStarts",
            "TPG Growth",
            "TI Platform Management",
            "Dragoneer Investment Group",
            "Owl Ventures",
            "Next Coast Ventures",
            "Genesis Capital",
            "Intel Capital",
            "\tFrontier Ventures",
            "Redpoint Ventures China",
            "China Capital Investment Group",
            "IFC",
            "Pear",
            "Stellaris Venture Partners",
            "Casa Verde Capital",
            "Bezos Expeditions",
            "Bnk To The Future",
            "SoGal Ventures",
            "Sozo Ventures",
            "SEEK",
            "GMO VenturePartners",
            "Omidyar Network",
            "Refactor Capital",
            "DFJ DragonFund",
            "Goldman Sachs Asset Management",
            "Atlantic Food Labs",
            "NextView Ventures",
            "Kleiner Perkins Caulfield & Byers",
            "AU21",
            "Altimeter Capital",
            "China Broadband Capital",
            "Fairfax Financial Holdings",
            "dmg ventures",
            "Venrock",
            "Wing Venture Capital",
            "Emerge",
            "Huagai Capital",
            "Wakefield Group",
            "Caisse de depot et placement du Quebec",
            "Honeywell",
            "Inclusive Capital Partners",
            "Silverlink Capital",
            "Alumni Ventures Group",
            "Social Capital",
            "Trammell Ventures",
            "BDC Venture Capital",
            "Madrone Capital Partners",
            "Sigma Prime Ventures",
            "Intact Ventures",
            "Ballast Point Ventures",
            "Breega Capital",
            "MindWorks Ventures",
            "Mayfield Fund",
            "\tOutrun Ventures",
            "Hundreds Capital",
            "Institutional Venture Partners",
            "Almaz Capital Partners",
            "Chiratae Ventures",
            "Signal Peak Ventures",
            "K2VC",
            "Zeev Ventures",
            "Not Boring Capital",
            "China Internet Investment Fund",
            "Co-Energy Finance",
            "Venture51",
            "K2 Global",
            "Straumann",
            "Access Industries",
            "Equal Ventures",
            "SEB Venture Capital",
            "Blume Ventures",
            "Pantera Capital",
            "NewAlpha",
            "Array Ventures",
            "Shanghai Puyin Industry",
            "Oriza Equity Investment",
            "Vertex Ventures",
            "Contour Venture Partners",
            "Sway Ventures",
            "Upper90",
            "Activant Capital Group",
            "Questa Capital",
            "Munich Re Ventures",
            "Big Bets",
            "Transformation Capital",
            "Astanor Ventures",
            "Energize Ventures",
            "Expa",
            "Rembrandt Venture Partners",
            "Advance Venture Partners",
            "Chicago Ventures",
            "Madera Technology Partners",
            "Upfront Ventures",
            "Polaris Partners",
            "Source Code Capital",
            "New Hope Fund",
            "Anthem Venture Partners",
            "Bling Capital",
            "Sequoia Capital India,Lightspeed India Partners",
            "Galeo Ventures",
            "Fifty Years Fund",
            "Lockheed Martin Ventures",
            "GSR Ventures",
            "Advancit Capital",
            "Globis Capital Partners",
            "Starr Investment Holdings",
            "Expedia Inc.",
            "M13",
            "Promecap",
            "Vertex Ventures China",
            "Benhcmark",
            "New Horizon Capital",
            "Boyu Capital",
            "01 Advisors",
            "Trifecta Capital Advisors",
            "Western Capital Management",
            "Centurium Capital",
            "Elevar Equity",
            "Richland Equities",
            "DSC Investments",
            "Merrysunny Wealth",
            "Uniqa Ventures",
            "TriplePoint Capital",
            "D1 Capita Partners",
            "Banner Ventures",
            "CVF Capital Partners",
            "Slow Ventures",
            "Susa Ventures",
            "Holtzbrinck Ventures",
            "EQT Partners",
            "Geely",
            "China State Capital Venture Capital Fund",
            "Wonder Ventures",
            "Riverwood Capital",
            "Fidelity Investment",
            "Quona Capital",
            "China Environmental Protection Industry",
            "Oak Investment Partners",
            "Invus Group",
            "Ireland Strategic Investment Fund",
            "Alaska Permanent Fund",
            "Ignition Partners",
            "OpenView Venture Partners",
            "Global Logistic Properties",
            "QC Capital",
            "Carrick Capital Partners",
            "TDK Ventures",
            "Toscafund Asset Management",
            "GCP Capital Partners",
            "PUC",
            "Baseline Ventures",
            "Grayhawk Capital",
            "Version One Ventures",
            "TPG Alternative & Renewable Technologies",
            "Blu Venture Investors",
            "Alibaba Group",
            "Ridge Ventures",
            "Xiaomi",
            "Vertex Ventures Israel",
            "Kima Ventures",
            "Goodwater Capital",
            "Chromo Invest",
            "Hyde Park Venture Partners,\tFundersClub. Bain Capital Ventures",
            "Borui Capital",
            "Lowercase Capital",
            "Alpha Wave Global",
            "BOLDstart Ventures",
            "Greycroft",
            "CDIB Capital",
            "58.com",
            "Flint Capital",
            "Blackstone",
            "Entree Capital",
            "Kae Capital",
            "GE Ventures",
            "Hanaco Venture Capital",
            "Zeal Capital Partners",
            "FJ Labs",
            "OMERS Ventures",
            "TVS Capital",
            "Funa Yuanchuang Technology",
            "Yabeo Capital",
            "Kefa Capital",
            "Eleation Capital",
            "Founders Fund. Accel",
            "Makers Fund",
            "Liberty Gloval Ventures",
            "Smilegate Investment",
            "Softbank Group",
            "Coatue Management",
            "Revolution Ventures",
            "next47",
            "MenloVentures",
            "Softbank Ventures Asia",
            "Valiant Capital Partners",
            "Viola Ventures",
            "C5 Capital",
            "Carlson Private Capital Partners,/td>",
            "Warmsun Holding",
            "Cobalt Capital",
            "enaya Capital",
            "Sapphire Ventures",
            "SDIC CMC Investment Management",
            "Global Catalyst Partnera",
            "Origin Ventures",
            "Koch Disruptive Technologies",
            "V FUND",
            "GSV Ventures",
            "RRE Ventures",
            "Wellington Management",
            "Lightspeed China Partners",
            "Benchmark",
            "Company K Partners",
            "Trinity Ventures",
            "SingulariTeam",
            "Temasek Holdings Ltd.",
            "N5 Capital",
            "Mayfield",
            "Lightspeed India Partners",
            "NewView Capital",
            "Matrix Partners China",
            "Newsion Venture Capital",
            "CDH Investments",
            "OLX Group",
            "BP Ventures",
            "Hongtai Capital Holdings",
            "Nexus Venture Partners",
            "Qumra Capital",
            "CR Capital Mgmt",
            "China Fortune Ocean",
            "Nortzone Ventures",
            "JMI Equity",
            "Telling Telecommunication Holding Co.",
            "National Grid Partners",
            "Artiman Ventures",
            "Hemisphere Ventures",
            "Insignia Ventures Partners",
            "Grab",
            "Trustbridge Partners",
            "China Grand Prosperity Investment",
            "GP Capital",
            "FAW Group",
            "FANUC",
            "ARCH Venture Partners",
            "Founder Collective",
            "Draft Ventures",
            "Legend Star",
            "Otter Rock Capital",
            "Accomplice",
            "Warburg Pincus",
            "TA Associates",
            "Drive Capital",
            "BMO Capital",
            "KTB Ventures",
            "Target Global",
            "Khosla Ventures",
            "Breakthrough Energy Ventures",
            "SDP Investment",
            "Stripes Group",
            "China Minsheng Investment Group",
            "Clocktower Technology Ventures",
            "CITIC Securities International",
            "Gron Ventures",
            "ION Crossover Partners",
            "H Capital",
            "Uncork Capital",
        ]
        self.assertEqual(sorted(actual_result), sorted(expected_result))

    def test_fifty_entries(self):
        """Test case 2 using fifty.csv with fifty rows."""
        actual_result = self.tasks_50.get_investors()
        expected_result = [
            "Andreessen Horowitz",
            "Founder Collective",
            "MindWorks Ventures",
            "Draft Ventures",
            "capitalG",
            "Addition",
            "Activant Capital",
            "None",
            "Greylock Partners",
            "DFJ Growth Fund",
            "ES Ventures",
            "Y Combinator",
            "Caffeinated Capital",
            "BDT Capital Partners",
            "KKR",
            "LTW Capital",
            "DST Global",
            "Smash Ventures",
            "Salesforce Ventures",
            "Lightspeed Venture Partners",
            "Advent International",
            "Storm Ventures",
            "Legend Capital",
            "Founders Fund",
            "Hillhouse Capital Management",
            "New Enterprise Associates",
            "Venrock",
            "CRV",
            "Longfor Capitalm",
            "Upper90",
            "LowercaseCapital",
            "RiverPark Ventures",
            "Tribe Capital",
            "Blackbird Ventures",
            "IDG Capital",
            "Gaorong Capital",
            "Sound Ventures",
            "Greenoaks Capital Management",
            "Coatue Management",
            "Accel",
            "Kleiner Perkins Caufield & Byers",
            "Spar Capital",
            "General Catalyst Partners",
            "Technology Crossover Ventures",
            "Tiger Global Management",
            "Vickers Venture Partners",
            "Sequoia Capital India",
            "Norwest Venture Partners",
            "Khosla Ventures",
            "Index Ventures",
            "Insight Partners",
            "IKEA GreenTech",
            "AltaIR Capital",
            "Forerunner Ventures",
            "General Catalyst",
            "Tencent Holdings",
            "Accel Partners",
            "Collaborative Fund",
            "Lightspeed India Partners",
            "Sequoia Capital China",
            "DJF",
            "Matrix Partners",
            "83North",
            "Breyer Capital",
            "SoftBank Group",
            "F-Prime Capital",
            "Accel India",
            "Rothenberg Ventures",
            "Homebrew",
            "Davidson Kempner Capital Management",
            "Softbank Group",
            "Google Ventures",
            "Shunwei Capital Partners",
            "Crosslink Capital",
            "Sina Weibo",
            "Sequoia Capital",
            "Temasek Holdings",
            "SAIF Partners",
            "SIG Asia Investments",
            "Battery Ventures",
            "Venture51",
            "Anthos Capital",
            "Ribbit Capital",
            "ZhenFund",
            "Institutional Venture Partners",
            "index Ventures",
            "Tencent",
            "Boyu Capital",
            "Qualcomm Ventures",
            "Yunfeng Capital",
            "Thirty Five Ventures",
            "General Atlantic",
            "GGV Capital",
            "Xiang He Capital",
            "Draper Fisher Jurvetson",
            "Warbug Pincus",
            "Felicis Ventures",
            "North Bridge Growth Equity",
        ]
        self.assertEqual(sorted(actual_result), sorted(expected_result))

    def test_ten_entries(self):
        """Test case 3 using ten.csv with ten rows."""
        actual_result = self.tasks_10.get_investors()
        expected_result = [
            "Battery Ventures",
            "Matrix Partners",
            "General Atlantic",
            "KKR",
            "New Enterprise Associates",
            "Smash Ventures",
            "Rothenberg Ventures",
            "Blackbird Ventures",
            "LowercaseCapital",
            "Sequoia Capital China",
            "Kleiner Perkins Caufield & Byers",
            "Softbank Group",
            "Founders Fund",
            "Institutional Venture Partners",
            "Sequoia Capital",
            "Khosla Ventures",
            "SIG Asia Investments",
            "capitalG",
            "Tiger Global Management",
            "Insight Partners",
            "Andreessen Horowitz",
            "Sina Weibo",
            "Collaborative Fund",
            "Draper Fisher Jurvetson",
            "Tencent Holdings",
            "DST Global",
        ]
        self.assertEqual(sorted(actual_result), sorted(expected_result))


if __name__ == "__main__":
    unittest.main()
